spring.application.name=stylefit

spring.datasource.url=jdbc:mysql://localhost:3306/stylefit
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

segmind.api.url=https://api.segmind.com/v1/idm-vton
segmind.api.key=SG_54db5c03897a165e
